repos:
- repo: https://github.com/pre-commit/pre-commit-hooks
  rev: v3.4.0
  hooks:
  - id: check-added-large-files
  - id: check-case-conflict
  - id: check-merge-conflict
  - id: check-symlinks
  - id: check-yaml
  - id: debug-statements
  - id: trailing-whitespace
  - id: fix-encoding-pragma
- repo: https://github.com/psf/black
  rev: stable
  hooks:
  - id: black
    language_version: python3.10
